default_platform :ios

before_all do
  setup_ci if is_ci
end

lane :unit_tests do
  run_tests(
    scheme: "UnitTests",
    device: "iPhone 14 (16.4)",
    derived_data_path: "dist"
  )
end

lane :integration_tests do
  run_tests(
    scheme: "IntegrationTests",
    device: "iPhone 14 (16.4)",
    derived_data_path: "dist"
  )
end

lane :atb_uitests do
  run_tests(
    scheme: "AtbUITests",
    device: "iPhone 14 (16.4)",
    derived_data_path: "dist"
  )
end

lane :performance_tests do
  run_tests(
    scheme: "PerformanceTests",
    device: "iPhone 14 (16.4)",
    derived_data_path: "dist"
  )
end

lane :build do
  build_app(
    scheme: "DuckDuckGo",
    configuration: "Debug",
    skip_codesigning: true,
    skip_package_ipa: true,
    derived_data_path: "dist",
    cloned_source_packages_path: "SourcePackages"
  )
end
