default_platform :ios

before_all do
  setup_circle_ci
end

desc "Run UnitTests"
lane :unit_test do
  run_tests(
    scheme: "UnitTests",
    device: "iPhone 13 (15.5)",
    derived_data_path: "dist"
  )
end
