default_platform :ios

before_all do
  setup_ci if is_ci
end

lane :atb_uitests do
  run_tests(
    scheme: "AtbUITests",
    device: "iPhone 14 (16.2)",
    derived_data_path: "dist"
  )
end

lane :unittests do
  run_tests(
    scheme: "UnitTests",
    device: "iPhone 14 (16.2)",
    derived_data_path: "dist"
  )
end

lane :build do
  match(type: "adhoc")
  build_app(
    scheme: "AdhocDebug",
    export_method: "ad-hoc",
    derived_data_path: "dist"
  )
end
